---
title: "species responses"
author: "Richard J. Telford"
date: "January 25, 2017"
output: html_document
---

```{r setup, include=FALSE, echo = FALSE, cache = FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE, message = FALSE, warning = FALSE, fig.height = 5.4, fig.width = 8)
knitr::read_chunk("weather_plots.R")
knitr::read_chunk("phenology.R")

```

## Climate change

```{r loadWeather, include = FALSE}

```
```{r loadPhenology}
```
  
```{r theme}
#sets global theme for figures
th <- theme_bw(base_size = 15)
```

## Date of first flowering

```{r first_flowering, include = FALSE}
```



## Correlation of first flowering with temperature

```{r mergeClimateCorrelate}
```


## Regression of first flowering against March temperature



## Can phenological change keep up with climate?
```{r regressions}
firstflowerReg <- first_floweringClim %>%
  filter(variable == "temperature") %>%
  select(-nyear, -year) %>%
  mutate(first = as.vector(first), last = as.vector(last), maxDate = as.vector(maxDate)) %>%
  group_by(species, month, median, timing, transect) %>%
  do(tidy(lm(first ~ value, data = .))[2, , drop = FALSE]) %>%
  mutate(month2 = ymd(paste0("2017-", month, "-1")))

```
  
```{r seasonalVelocity}
```
  
  
```{r}  
for( i in unique(firstflowerReg$species)){
g <- filter(firstflowerReg, species == i) %>% 
     mutate(month2 = case_when(transect == "t36" ~ month2 - 3,
                               transect == "t37" ~ month2 - 1,
                               transect == "t38" ~ month2 + 1,
                               transect == "t39" ~ month2 + 3))%>% 
     ggplot(aes(x = month2, y = estimate, ymax = estimate + 1.96 * std.error, min = estimate - 1.96 * std.error, colour = transect)) +
  geom_pointrange() +
  scale_x_date(name = "Month", date_breaks = "1 month", date_labels = "%b") +
  labs(y = "Effect, days/°C", xlab = "Month") +
  geom_segment(aes(x = median, y = -Inf, yend = Inf, xend = median), colour = "grey50", linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed", colour = "grey70") 
  

g2 <- g +  geom_ribbon(data = filter(seasonalwarming, doy < 180 & doy > 30), mapping = aes(x = doy2, y = -1/Estimate, ymax = -1/(Estimate + 1.96 * `Std. Error`), ymin = -1/(Estimate - 1.96 * `Std. Error`)), alpha = 0.4, fill = "red", inherit.aes = FALSE) +
  geom_line(data = filter(seasonalwarming, doy < 180 & doy > 30), mapping = aes(x = doy2, y = -1/Estimate), colour = "red", inherit.aes = FALSE) +
  coord_cartesian(ylim = c(-20, 5))

print(g2 + th + ggtitle(i))
}
```

